### ISSUE TITLE
Need an instruction document for others to try this website

### ISSUE THREAD

**Issue by sjiang1** [COSC381-2022Winter/githubflow-practice-sjiang1#1]
The document should have step-by-step instructions to start this website from scratch. For now, we don't need deployment instructions. 

- [x] have a fresh copy of this repository
- [x] start the website in this fresh copy and write every step down
- [x] format the document so that it's easy to follow

**Comment by aaleryani99** [comment]
I can comment

**Comment by Nick-Garska** [comment]
i am here

**Comment by zartaj10** [comment]
I can comment

**Comment by Ariel-maxcoder** [comment]
done

**Comment by halsowadi** [comment]
Leaving a comment

**Comment by khammerm** [comment]
Hello World

**Comment by AndrewKilian** [comment]
yes

**Comment by jgenove1** [comment]
Hello, professor

**Comment by brandonijones** [comment]
this is a comment
